config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'sessions#home'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/profile', to: 'users#show'

  get '/favorites', to: 'candidates#favorites'

  get '/auth/facebook/callback', to: 'sessions#fb_create'

  resources :contributors
  resources :contributions
  resources :candidates
  resources :users, except: [:new, :create]

  Rails.application.routes.draw do

    resources :contributors, only: [:show, :new, :create] do
      resources :contributions, only: [:show, :index, :new]
    end

    resources :candidates, only: [:show, :new, :create] do
      resources :contributions, only: [:show, :index, :new]
    end

    # root 'contributions#index'
  end

  Rails.application.routes.draw do

    resources :candidates, except: [:edit, :new] do
      resource :favorite, only:[:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :contributions, dependent: :destroy
  has_many :contributors, through: :contributions
  has_many :favorites, dependent: :destroy
  ##has_many :users, through: :favorites --??? aliases?? favorited_candidates?
  validates :first_name, presence: true

  scope :all_in_order, -> { order(last_name: :asc)}
  scope :favorited_by, -> (user_id) { joins(:favorites).where(favorites: { user: User.where(id: user_id) }) }

  def full_name
    if self.last_name.present?
      self.first_name + " " + self.last_name
    else
      self.first_name
    end
  end

  def self.favorited_candidates(current_user)
    @current_user = current_user
    @candidates = []

    @current_user.favorites.each do |fav|
      @candidates << Candidate.find_by(id: fav.candidate_id)
    end

    @candidates.sort_by(&:last_name)
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, except: [:index, :favorites, :new, :create]
  before_action :current_user, only: [:favorites, :show]

  def index
    if params[:last_name]
      @candidates = Candidate.where('last_name LIKE ?', "%#{params[:last_name]}%")
    else
      @candidates = Candidate.all_in_order
    end

    respond_to do |format|
      format.html
      format.json { render json: @candidates }
    end
  end

  def favorites
    @candidates = Candidate.favorited_candidates(@current_user)

    if @candidates.empty?
      redirect_to candidates_path, flash: {notice: "You currently have no favorites."}
    end
  end

  def show
    @current_user = User.find(session[:user_id])

    respond_to do |format|
      format.html
      format.json { render json: @candidate }
    end
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      redirect_to candidate_path(@candidate)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @candidate.update(candidate_params)
    redirect_to candidate_path(@candidate)
  end

  def destroy
    @candidate.destroy
    redirect_to candidates_path
  end

  private

  def current_user
    @current_user = User.find(session[:user_id])
  end

  def find_candidate
    @candidate = Candidate.find(params[:id])
  end

  def candidate_params
    params.require(:candidate).permit(:first_name, :last_name, :party_affiliation, :office_position, :location, :platform_outline, :favorites_count)
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_favorited.html.erb
<% if @current_user.favorited?(@candidate) %>
  Favorited.
  <%= link_to " Remove from Favorites?", candidate_favorite_path(@candidate), method: :delete %>
<% else %>
  <%= link_to "Add to Favorites.", candidate_favorite_path(@candidate), method: :post %>
<% end %>

<% if @candidate.favorites_count.nil? %>
  This candidate has no favorites.
<% else %>
  This candidate has <%= @candidate.favorites_count %> favorites.
<% end %>

app/views/candidates/_form.html.erb
<%= form_for @candidate do |f| %>
  <%= render partial: 'layouts/errors', locals: {object: @candidate} %>

  <%= f.label :first_name, "First Name" %>
  <%= f.text_field :first_name, placeholder: "ex. Jane" %><br><br>

  <%= f.label :last_name, "Last Name" %>
  <%= f.text_field :last_name, placeholder: "ex. Smith" %><br><br>

  <%= f.label :party_affiliation, "Party Affiliation" %>
  <%= f.text_field :party_affiliation, placeholder: "Enter Party Name Here or Select One From Dropdown", list: "party_affiliation_autocomplete" %><br><br>
  <datalist id="party_affiliation_autocomplete">
    <option value="Democrat">
    <option value="Independent">
    <option value="Republican">
  </datalist>

  <%= f.label :office_position, "Running For" %>
  <%= f.text_field :office_position, placeholder: "ex. President" %><br><br>

  <%= f.label :location, "Current Office and/or State" %>
  <%= f.text_field :location, placeholder: "ex. Senator from Hawaii" %><br><br>

  <%= f.label :platform_outline, "Platform Outline" %>
  <%= f.text_area :platform_outline, placeholder: "Describe platform here." %><br><br>

  <%= f.submit 'List Candidate' %>
<% end %>

app/views/candidates/_index.html.erb
<%= link_to 'List A Candidate', new_candidate_path %><br><br>

<% @candidates.each do |candidate| %>
  <li><%= link_to candidate.full_name, candidate_path(candidate) %></li>
<% end %>

app/views/candidates/edit.html.erb
<h3>Make Changes to this Candidate Below</h3>

<%= render 'form' %>

app/views/candidates/favorites.html.erb
<h1>Your Favorite Candidates</h1>

<%= render 'index' %>

app/views/candidates/index.html.erb
<h1>Candidates</h1>

<%= form_tag("/candidates", method: :get) do %>
  Candidate Last Name <%= text_field_tag :last_name, params[:last_name] %>
  <%= submit_tag 'Search' %>
<% end %><br>

<%= render 'index' %>

app/views/candidates/new.html.erb
<h3>Fill In Below to List a New Candidate</h3>

<%= render 'form' %>

app/views/candidates/show.html.erb
<h2><%= @candidate.full_name %></h2> <%= render 'favorited' %>
  <h3><%= @candidate.party_affiliation %></h3>
  <h3><%= @candidate.location %></h3>
    <p>Running for <%= @candidate.office_position %></p>
    <p>Key Issues: <%= @candidate.platform_outline %></p>

    <a href="#" data-id="<%=@candidate.id%>" class="candidate_contribution_link" onclick="getCandidateContributions(); return false;"><p>See All Contributions</p></a>
    <div id="main"></div><br>

<%= button_to 'Edit Candidate', edit_candidate_path(@candidate), method: :get %><br>
<%= button_to 'Delete Candidate', candidate_path(@candidate), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>