config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'sessions#home'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/profile', to: 'users#show'

  get '/favorites', to: 'candidates#favorites'

  get '/auth/facebook/callback', to: 'sessions#fb_create'

  resources :contributors
  resources :contributions
  resources :candidates
  resources :users, except: [:new, :create]

  Rails.application.routes.draw do

    resources :contributors, only: [:show, :new, :create] do
      resources :contributions, only: [:show, :index, :new]
    end

    resources :candidates, only: [:show, :new, :create] do
      resources :contributions, only: [:show, :index, :new]
    end

    # root 'contributions#index'
  end

  Rails.application.routes.draw do

    resources :candidates, except: [:edit, :new] do
      resource :favorite, only:[:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :candidate, optional: true
  belongs_to :contributor, optional: true

  after_save :assign_size

  validates :amount, presence: true, numericality: {only_integer: true, greater_than: 0}
  validates :candidate_name, presence: true
  validates :contributor_name, presence: true
  validates :date, presence: true, format: {with: /\d{2}\/\d{2}\/\d{4}/}
  # validates_each :date do |record, attr, value|
  #   begin
  #     Date.parse(value)
  #   rescue
  #     record.errors.add(attr, "Invalid date")
  #   end
  # end

  scope :all_by_date, -> { order(date: :desc)}

  def candidate_name=(candidate_name)
    if !candidate_name.nil? && candidate_name != ""
      first_name = candidate_name.split(" ")[0]
      last_name = candidate_name.split(" ")[1]

      if last_name == nil
        last_name = " "
      end

      self.candidate = Candidate.find_or_create_by(first_name: first_name, last_name: last_name)
    end
  end

  def candidate_name
    self.candidate ? self.candidate.full_name : nil
  end

  def contributor_name=(contributor_name)
    self.contributor = Contributor.find_or_create_by(name: contributor_name)
  end

  def contributor_name
    self.contributor ? self.contributor.name : nil
  end

  def assign_size
    if self.amount > 199
      self.size = "Large"
    else
      self.size = "Small"
    end
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :find_contribution, only: [:show, :edit, :update, :destroy]

  def index
    if params[:contributor_id]
      @contributions = Contributor.find(params[:contributor_id]).contributions.all_by_date
    elsif params[:candidate_id]
      @contributions = Candidate.find(params[:candidate_id]).contributions.all_by_date
    else
      @contributions = Contribution.all_by_date
    end

    render json: @contributions
  end

  def show
    render json: @contribution
  end

  def new
    @contribution = Contribution.new(contributor_id: params[:contributor_id], candidate_id: params[:candidate_id])
  end

  def create
    @contribution = Contribution.new(contribution_params)
    if @contribution.save
      render json: @contribution, status: 201
    else
      render json: { errors: @contribution.errors.full_messages }, status: 422
    end
  end

  def edit
  end

  def update
    @contribution.update(contribution_params)
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @contribution}
    end
  end

  def destroy
    @contribution.destroy
    render json: @contributions
  end

  private

  def find_contribution
    @contribution = Contribution.find(params[:id])
  end

  def contribution_params
    params.require(:contribution).permit(:amount, :date, :contributor_name, :candidate_name, :contributor_id, :candidate_id)
  end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_form.html.erb
<%= form_for @contribution do |f| %>
  <%= render partial: 'layouts/errors', locals: {object: @contribution} %>

  <%= f.label :contributor_name, "Contributor Name" %>
  <%= f.text_field :contributor_name, placeholder: "ex. Jane Smith" %><br><br>

  <%= f.label :candidate_name, "Candidate Name" %>
  <%= f.text_field :candidate_name, placeholder: "ex. Jane Smith" %><br><br>

  <%= f.label :amount, "Amount $" %>
  <%= f.text_field :amount, placeholder: "1000" %><br><br>

  <%= f.label :date %>
  <%= f.text_field :date, placeholder: "mm/dd/yyyy" %><br><br>

  <%= f.submit 'Contribute' %>
<% end %>

app/views/contributions/edit.html.erb
<h3>Make Changes to This Contribution Below</h3>

<%= render 'form' %>

app/views/contributions/index.html.erb
<h1>Contributions</h1>

<p><%= link_to 'List a New Contribution', new_contribution_path %></p>

<div id="main">
  <table id="table">
    <thead>
      <tr>
        <th>Candidate</th>
        <th>Contribution</th>
        <th>Contributor</th>
        <th>Date</th>
      </tr>
    </thead>

    <tbody>
      <% @contributions.each do |c| %>
        <tr>
          <td><%= link_to c.candidate_name, candidate_path(c.candidate) %></td>
          <td><%= link_to c.amount, contribution_path(c) %></td>
          <td><%= link_to c.contributor_name, contributor_path(c.contributor) %></td>
          <td><%= c.date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/contributions/new.html.erb
<h3>Fill In Below to List a Contribution</h3>

<%= render 'form' %>

app/views/contributions/show.html.erb
<h2><%= link_to @contribution.candidate_name, candidate_path(@contribution.candidate) %></h2>
  <h3>Amount: $<%= @contribution.amount %></h3>
  <h3>Date: <%= @contribution.date %></h3>
  <h3>Contributor:<%= link_to @contribution.contributor_name, contributor_path(@contribution.contributor) %></h3>

<%= button_to "Edit Contribution", edit_contribution_path(@contribution), method: :get %><br>
<%= button_to 'Delete Contribution', contribution_path(@contribution), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>