config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'sessions#home'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/profile', to: 'users#show'

  get '/favorites', to: 'candidates#favorites'

  get '/auth/facebook/callback', to: 'sessions#fb_create'

  resources :contributors
  resources :contributions
  resources :candidates
  resources :users, except: [:new, :create]

  Rails.application.routes.draw do

    resources :contributors, only: [:show, :new, :create] do
      resources :contributions, only: [:show, :index, :new]
    end

    resources :candidates, only: [:show, :new, :create] do
      resources :contributions, only: [:show, :index, :new]
    end

    # root 'contributions#index'
  end

  Rails.application.routes.draw do

    resources :candidates, except: [:edit, :new] do
      resource :favorite, only:[:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  has_many :contributions, dependent: :destroy
  has_many :candidates, through: :contributions

  validates :name, presence: true
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
  before_action :find_contributor, only: [:show, :edit, :update, :destroy]

  def index
    @contributors = Contributor.all

    respond_to do |format|
      format.html
      format.json { render json: @contributors }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @contributor }
    end
  end

  def new
    @contributor = Contributor.new
  end

  def create
    @contributor = Contributor.new(contributor_params)

    if @contributor.save
      redirect_to contributor_path(@contributor)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @contributor.update(contributor_params)
    redirect_to contributor_path(@contributor)
  end

  def destroy
    @contributor.destroy
    redirect_to contributors_path
  end

  private

  def find_contributor
    @contributor = Contributor.find(params[:id])
  end

  def contributor_params
    params.require(:contributor).permit(:name, :category, :industry_affiliation)
  end
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/views/contributors/_form.html.erb
<%= form_for @contributor do |f| %>
  <%= render partial: 'layouts/errors', locals: {object: @contributor} %>

  <%= f.label :name %>
  <%= f.text_field :name %><br><br>

  <%= f.label :industry_affiliation, "Industry Affiliation" %>
  <%= f.text_field :industry_affiliation, placeholder: "Enter or Select Industry", list: "industry_affiliation_autocomplete" %><br><br>
  <datalist id="industry_affiliation_autocomplete">
    <option value="Finance/Insurance/Real Estate">
    <option value="Ideology/Single-Issue">
    <option value="Misc Business">
    <option value="Technology">
    <option value="Health">
    <option value="Communications/Electronics">
    <option value="Lawyers & Lobbyists">
    <option value="Labor">
    <option value="Energy/Natural Resources">
    <option value="Agribusiness">
    <option value="Construction">
    <option value="Transportation">
    <option value="Defense">
    <option value="Not Applicable">
    <option value="Other">
  </datalist>

  <%= f.submit 'List Contributor' %>
<% end %>

app/views/contributors/edit.html.erb
<h3>Make Changes to This Contributor Profile Below</h3>

<%= render 'form' %>

app/views/contributors/index.html.erb
<h1>Contributors</h1>
<%= link_to 'List A Contributor', new_contribution_path %><br><br>

<% @contributors.each do |contributor| %>
  <li><%= link_to contributor.name, contributor_path(contributor) %></li>
<% end %>

app/views/contributors/new.html.erb
<h3>Fill In Below to List a New Contributor</h3>

<%= render 'form' %>

app/views/contributors/show.html.erb
<h2><%= @contributor.name %></h2>
  <h3>Industry: <%= @contributor.industry_affiliation %></h3>
  <a href="#" data-id="<%=@contributor.id%>" class="contributor_contribution_link" onclick="getContributorContributions(); return false;"><p>See All Contributions</p></a>
  <div id="main"></div><br>

<%= button_to 'Edit Contributor', edit_contributor_path(@contributor), method: :get %><br>
<%= button_to 'Delete Contributor', contributor_path(@contributor), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>