config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'sessions#home'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/profile', to: 'users#show'

  get '/favorites', to: 'candidates#favorites'

  get '/auth/facebook/callback', to: 'sessions#fb_create'

  resources :contributors
  resources :contributions
  resources :candidates
  resources :users, except: [:new, :create]

  Rails.application.routes.draw do

    resources :contributors, only: [:show, :new, :create] do
      resources :contributions, only: [:show, :index, :new]
    end

    resources :candidates, only: [:show, :new, :create] do
      resources :contributions, only: [:show, :index, :new]
    end

    # root 'contributions#index'
  end

  Rails.application.routes.draw do

    resources :candidates, except: [:edit, :new] do
      resource :favorite, only:[:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <p>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this post from being saved:
    </p>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<h3><a href="/home">Dollars for Change</a></h3>
  <div class="navigation">
    <ul>
      <% if session[:user_id].present? %>
        <%= link_to "Return to Explore", user_path(session[:user_id]) %> |
      <% end %>
      <%= link_to "Candidates", candidates_path %> |
      <%= link_to "Contributors", contributors_path %> |
      <% if session[:user_id].present? %>
        <%= link_to 'Log Out', logout_path %>
      <% end %>
    </ul>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dollars for Change</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

    <%= yield %>

    </div>

  </body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dollars for Change</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h3><a href="/home">Dollars for Change</a></h3>

    <%= yield %>

  </body>
</html>